
server:
  port: 8888

spring:
  application:
    name: notification-service

management:
  observations:
    annotations:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  otlp:
    metrics:
      export:
        enabled: false

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces


logging:
  pattern:
    console: "%d{ISO8601} %-5level [%thread] %X{traceId} %X{spanId} %logger{36} - %msg%n"