version: '3.8'

# =============================================================================
# Запуск: docker-compose --env-file .env up -d
# Остановка: docker-compose down -v (удалит volumes)
#
# Компоненты:
#   postgres     - база данных (хранит заказы)
#   order-service - само приложение Spring Boot
#   prometheus   - сбор метрик (хранит 15 дней)
#   grafana      - визуализация (дашборды)
# =============================================================================

services:

  # ---------------------------------------------------------------------------
  # Spring Boot приложение
  # ---------------------------------------------------------------------------
  order-service:
    build: .
#      context: .                    # Текущая директория
#      dockerfile: Dockerfile
#      args:
#        # Аргументы сборки (только метаинформация)
#        APP_VERSION: ${APP_VERSION}  # Версия приложения для меток в образе
    container_name: orderhub_app
    ports:
      - "7771:8081"           # Проброс порта наружу
    networks:
      - order-service-network
    environment:
      # -----------------------------------------------------------------------
      # Подключение к БД (runtime)
      # -----------------------------------------------------------------------
      SPRING_DATASOURCE_URL: jdbc:postgresql://order_db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}  # Секрет!

      # -----------------------------------------------------------------------
      # Для миграций и прямых запросов (если нужно внутри приложения)
      # -----------------------------------------------------------------------
      POSTGRES_HOST: order_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      # -----------------------------------------------------------------------
      # JPA настройки
      # -----------------------------------------------------------------------
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}  # validate в production

# -------------------------------------------------------------------------------
# Изолированная сеть для сервисов
# -------------------------------------------------------------------------------
networks:
  order-service-network:
    name: order-service-network
    external: true