version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: order_db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-order}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

    command:
      - "postgres"
      - "-c"
      - "max_connections=100"

volumes:
  postgres_data:
