
server:
  port: 8081


spring:
  application:
    name: project

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:order}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    enabled: true
    change-log: classpath:/db/changelog/changelog_master.yaml

  jooq:
    sql-dialect: postgres




management:
  info:
    env:
      enabled: true
    git:
      mode: full
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - prometheus
          - loggers

info:
  app:
    name: "Order service"
    version: "0.0.1"
    description: "Сервис заказов"

logging:
  level:
    org.hibernate.sql: DEBUG
    root: info