
server:
  port: ${ORDER_SERVICE_PORT:8081}


spring:
  application:
    name: order-service

  profiles:
    active: default

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    enabled: true
    change-log: classpath:/db/changelog/changelog_master.yaml

  jooq:
    sql-dialect: postgres




management:
  observations:
    annotations:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  otlp:
    metrics:
      export:
        enabled: false

  opentelemetry: # в Boot 4 предпочтительнее этот путь
    tracing:
      export:
        otlp:
          endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

  prometheus:
    metrics:
      export:
        enabled: true
        descriptions: true

  metrics:
    distribution:
      percentiles-histogram:
        all: true
      slo:
        "[http.server.requests]": 50ms,100ms,200ms,500ms,1s,2s

  info:
    env:
      enabled: true
    git:
      mode: full
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - prometheus
          - loggers

info:
  app:
    name: "Order service"
    version: "0.0.1"
    description: "Сервис заказов"

logging:
  level:
    org.hibernate.sql: DEBUG
    root: info

url:
  notification-service: ${NOTIFICATION_SERVICE_URL}